### ISSUE TITLE
Handle class access modifiers

### ISSUE THREAD

**Issue by azuy212** [otv1/vue-property-decorator-to-vue-3-setup-api#1]
Currently, this script is not handling class access modifiers (private, public), causing the issue while converting.

`private testData: string | null = null;
`
`
public get testComputed() {
  return this.testData;
}`

**Comment by otv1** [comment]
Ok.

I will make an update later this week/weekend.

**Comment by otv1** [comment]
The script will now work with private/public. But please format your methods using multiline:
public get testComputed() { 
   return this.testData;
}

**Comment by otv1** [comment]
Closing
